services:
  countries-api:
    hostname: countries-api
    image: countriesapi
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env.production
    ports:
      - 8000:8000
