services:

  mongo:
    image: mongo
    restart: unless-stopped
    env_file: ".env.development"
    ports:
      - 27017:27017
    volumes:
      - mongoDB:/data/db


volumes:
  mongoDB:
    name: mongoDB
