name: countries-api-debug
services:
  countries-api:
    hostname: countries-api
    image: ysrckr/countries-api
    environment:
      - MODE=${MODE}
    command: ['--mode', '${MODE}']
    env_file:
      - .env.${MODE}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
      update_config:
        parallelism: 1
        delay: 10s
    networks:
      - api_network
    volumes:
      - ${PWD}/.env.${MODE}:/.env.${MODE}

networks:
  api_network:
    external: true
